### ISSUE TITLE
Some sections are missing

### ISSUE THREAD

**Issue by iandol** [bcdavasconcelos/ScrivQ#1]
In your sample PDF, you can see some sections like Introduction are missing:

![Screenshot 2023-06-16 at 09 38 01](https://github.com/bcdavasconcelos/ScrivQ/assets/153905/2c97075c-e093-46ca-b428-6bf898dd2731)

**Comment by bcdavasconcelos** [comment]
Thanks, Ian. `Section + Break` was attached to `As Is`. Fixed along with many other smaller issues in the last few commits. A problem remains, however:  https://github.com/bcdavasconcelos/ScrivQ/issues/2
