### ISSUE TITLE
Figures are overflowing the page

### ISSUE THREAD

**Issue by bcdavasconcelos** [bcdavasconcelos/ScrivQ#2]
Adding `column-page` (or `//| column: page`/`%%| column: page`) to these elements doesn't seem to fix the problem.

<img width="813" alt="image" src="https://github.com/bcdavasconcelos/ScrivQ/assets/35749099/7356e281-7c89-44dd-9e3f-58b68b437658">

**Comment by iandol** [comment]
Not sure what is going on, my template currently doesn't overflow: https://github.com/iandol/scrivomatic/blob/master/sample-output/Quarto.pdf — the markdown is here: https://github.com/iandol/scrivomatic/blob/master/sample-output/Quarto.qmd

I don't include any `//| column:` directives, but I don't think that is the issue. I do modify the geometry in my latex metadata which you don't do:

```yaml
geometry:
      #- showframe             # check the layout
      - top=2cm
      - bottom=2cm
      - head=1cm
      - foot=1cm
      - left=2cm
      - marginparwidth=4cm
      - textwidth=12cm
      - marginparsep=1cm
      - bindingoffset=0.5cm
```

This may solve the problem, we can use `showframe` option to help during debugging.

**Comment by bcdavasconcelos** [comment]
Thanks again for the feedback and the links, Ian.

I tried: 

- adding geometry settings;
- recalculating the type area using `\KOMAoptions{DIV=default}`;
- adding/removing`//| column:` directives;

In the end, I managed to fix the issue by adding the **class option** `oneside`. 

<img width="793" alt="image" src="https://github.com/bcdavasconcelos/ScrivQ/assets/35749099/f590c431-8ab4-46a8-9e11-feb840a5d932">
